INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (1, 'Clapison', 'sclapison0@discuz.net', true, 'Gembucket', false, 2751, 'gt6O9Z5');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (2, 'Kettel', 'ekettel1@salon.com', false, 'Gembucket', true, 2684, 'UmIOPHAkeEV');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (3, 'Lamputt', 'mlamputt2@hostgator.com', true, 'Asoka', false, 6104, 'EEbstkhrirVF');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (4, 'Miskin', 'cmiskin3@goo.ne.jp', false, 'Greenlam', true, 3586, 'qoHU1GRD1k');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (5, 'Stollen', 'cstollen4@nature.com', false, 'Fixflex', true, 5718, 'INq5yI');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (6, 'Timson', 'atimson5@jugem.jp', true, 'Tampflex', false, 6278, 'bT1OzZX72Ez');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (7, 'McClune', 'emcclune6@booking.com', true, 'Quo Lux', true, 7981, 'lbIgXquf');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (8, 'Partkya', 'gpartkya7@smugmug.com', false, 'Prodder', false, 2672, 'XalyjK');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (9, 'Di Napoli', 'wdinapoli8@theglobeandmail.com', false, 'Home Ing', true, 3658, 'lF4v7c');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (10, 'Allday', 'hallday9@zdnet.com', true, 'Holdlamis', false, 5955, 'gzjLjvpvDC');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (11, 'Timmis', 'ztimmisa@yale.edu', true, 'Tin', false, 7328, 'rhmolW');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (12, 'Cristoforo', 'ccristoforob@examiner.com', true, 'Duobam', true, 7740, '6ZJqraZLLdQ');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (13, 'Lortzing', 'slortzingc@thetimes.co.uk', true, 'Tempsoft', true, 6161, '07glHeQyS7IN');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (14, 'Guerola', 'jguerolad@sourceforge.net', false, 'Tampflex', false, 8254, 'xBSzcc');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (15, 'Drust', 'adruste@shop-pro.jp', true, 'Cardify', false, 5744, '0rFjyQ');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (16, 'Finlow', 'sfinlowf@soundcloud.com', true, 'Flowdesk', true, 8156, '1nFjGXxVtep');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (17, 'Fraschini', 'ffraschinig@php.net', false, 'Cookley', true, 1725, '3DcWwfnP');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (18, 'Di Roberto', 'fdirobertoh@ft.com', false, 'Quo Lux', true, 2730, 'VQN8bSdKm');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (19, 'Croll', 'ccrolli@webnode.com', true, 'Tampflex', true, 8360, 'PdcEol');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (20, 'Seivwright', 'cseivwrightj@imdb.com', false, 'Lotstring', false, 2552, 'fv6ld8XdN');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (21, 'Round', 'froundk@narod.ru', false, 'Matsoft', false, 6887, 'iVQjSy9r5');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (22, 'Fenimore', 'kfenimorel@buzzfeed.com', true, 'Konklux', true, 7741, 'T8IYBV2t');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (23, 'Faulks', 'sfaulksm@imageshack.us', true, 'Pannier', true, 7749, '986EbZATk2');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (24, 'Winterborne', 'dwinterbornen@usgs.gov', false, 'Keylex', false, 600, 'LrrHHo');
INSERT INTO users (id, name, email, writer, favorite, premium, followers, password) VALUES (25, 'Scamwell', 'oscamwello@house.gov', true, 'Sub-Ex', false, 1033, 'UC61ycfFD');

INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (1, 'Zamit', 'ikelway0@unicef.org', true, 'semper rutrum nulla nunc purus phasellus', 2199, 'LB');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (2, 'Sonsing', 'wkubatsch1@state.tx.us', true, 'ante vivamus tortor duis', 82, 'BA');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (3, 'Bitwolf', 'klodeke2@archive.org', false, 'risus semper porta volutpat', 2038, 'VN');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (4, 'Zathin', 'pshirt3@lulu.com', false, 'condimentum curabitur in libero ut massa volutpat convallis', 1740, 'NG');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (5, 'Konklux', 'sfowler4@ftc.gov', true, 'sed sagittis nam congue risus', 1392, 'PH');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (6, 'Bamity', 'cokynsillaghe5@unblog.fr', false, 'quam pede lobortis ligula sit amet eleifend pede libero', 3858, 'PH');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (7, 'Bigtax', 'lknill6@pbs.org', false, 'lectus pellentesque at nulla', 8844, 'SY');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (8, 'Voltsillam', 'jrudinger7@icio.us', false, 'praesent blandit lacinia erat vestibulum sed', 3246, 'CN');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (9, 'Ventosanzap', 'lnisco8@seattletimes.com', false, 'ut ultrices vel augue', 8310, 'UA');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (10, 'Asoka', 'vvacher9@nature.com', true, 'ipsum primis in faucibus', 2126, 'PH');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (11, 'Cardify', 'jalldaya@prlog.org', true, 'pulvinar nulla pede ullamcorper augue a', 8738, 'SE');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (12, 'Ronstring', 'gbaggb@goo.ne.jp', true, 'sit amet lobortis sapien sapien non mi integer', 6746, 'BR');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (13, 'Domainer', 'sfancourtc@deliciousdays.com', false, 'dui vel sem', 5297, 'SE');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (14, 'Stim', 'gdoryd@yandex.ru', true, 'risus semper porta volutpat quam pede lobortis ligula', 7913, 'CN');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (15, 'Subin', 'rdowarde@weibo.com', true, 'adipiscing molestie hendrerit at vulputate', 5931, 'PL');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (16, 'Transcof', 'tbowmakerf@ycombinator.com', true, 'odio curabitur convallis duis consequat dui nec nisi volutpat', 5435, 'DO');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (17, 'Zamit', 'shoggettsg@jugem.jp', false, 'neque sapien placerat ante nulla justo aliquam quis turpis', 1324, 'TZ');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (18, 'Stronghold', 'gsicilyh@wsj.com', true, 'mi in porttitor pede justo', 7678, 'ID');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (19, 'Hatity', 'imargiottai@apple.com', true, 'varius nulla facilisi cras non velit nec nisi vulputate', 5244, 'ID');
INSERT INTO articles (id, title, author, premium, content, times_read, genre) VALUES (20, 'Alpha', 'cboolej@360.cn', true, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 2684, 'CN');
