INSERT INTO songs (title, length, album, artist, track_num) values ('Customer-focused logistical attitude', 2.93, 'massa donec', 'Prodder', 10);
INSERT INTO songs (title, length, album, artist, track_num) values ('Managed zero tolerance flexibility', 3.35, 'felis', 'Redhold', 12);
INSERT INTO songs (title, length, album, artist, track_num) values ('Centralized hybrid Graphic Interface', 2.46, 'pellentesque at', 'Toughjoyfax', 8);
INSERT INTO songs (title, length, album, artist, track_num) values ('Synchronised attitude-oriented framework', 4.24, 'eu felis', 'Voyatouch', 20);
INSERT INTO songs (title, length, album, artist, track_num) values ('Streamlined asynchronous toolset', 3.42, 'eget eros elementum', 'Konklux', 21);
INSERT INTO songs (title, length, album, artist, track_num) values ('Cross-platform 5th generation groupware', 1.08, 'pellentesque ultrices mattis odio', 'Zoolab', 6);
INSERT INTO songs (title, length, album, artist, track_num) values ('Implemented responsive circuit', 4.47, 'non quam nec dui', 'Alphazap', 6);
INSERT INTO songs (title, length, album, artist, track_num) values ('Profound web-enabled contingency', 3.0, 'rutrum neque aenean', 'Stim', 12);
INSERT INTO songs (title, length, album, artist, track_num) values ('Triple-buffered client-server task-force', 2.3, 'convallis nulla neque', 'Ronstring', 11);
INSERT INTO songs (title, length, album, artist, track_num) values ('Ergonomic bottom-line extranet', 2.07, 'mauris', 'Andalax', 28);
INSERT INTO songs (title, length, album, artist, track_num) values ('Customer-focused dynamic complexity', 2.36, 'lacinia erat vestibulum', 'Home Ing', 24);
INSERT INTO songs (title, length, album, artist, track_num) values ('Vision-oriented zero defect model', 2.26, 'massa volutpat convallis morbi', 'Solarbreeze', 7);
INSERT INTO songs (title, length, album, artist, track_num) values ('Expanded 4th generation product', 2.18, 'integer ac neque', 'Bamity', 26);
INSERT INTO songs (title, length, album, artist, track_num) values ('Implemented multi-state throughput', 3.55, 'ut nulla sed accumsan', 'Bigtax', 21);
INSERT INTO songs (title, length, album, artist, track_num) values ('Re-contextualized scalable customer loyalty', 3.16, 'turpis a pede', 'Tres-Zap', 27);
INSERT INTO songs (title, length, album, artist, track_num) values ('Sharable client-server infrastructure', 4.33, 'cum', 'Voyatouch', 13);
INSERT INTO songs (title, length, album, artist, track_num) values ('Integrated fault-tolerant access', 1.42, 'eget elit sodales scelerisque', 'Opela', 25);
INSERT INTO songs (title, length, album, artist, track_num) values ('Front-line transitional capacity', 2.55, 'erat nulla tempus vivamus', 'Wrapsafe', 14);
INSERT INTO songs (title, length, album, artist, track_num) values ('Inverse background paradigm', 2.24, 'mauris', 'Treeflex', 15);
INSERT INTO songs (title, length, album, artist, track_num) values ('Secured empowering application', 1.74, 'vulputate luctus cum', 'Zamit', 8);
INSERT INTO songs (title, length, album, artist, track_num) values ('Cross-platform multi-state Graphical User Interface', 4.46, 'amet', 'Zontrax', 24);
INSERT INTO songs (title, length, album, artist, track_num) values ('Quality-focused intermediate forecast', 1.13, 'nulla mollis molestie lorem', 'Toughjoyfax', 8);
INSERT INTO songs (title, length, album, artist, track_num) values ('Decentralized analyzing framework', 1.99, 'morbi', 'Sonair', 12);
INSERT INTO songs (title, length, album, artist, track_num) values ('Down-sized solution-oriented help-desk', 1.77, 'luctus cum sociis natoque', 'Otcom', 10);
INSERT INTO songs (title, length, album, artist, track_num) values ('Automated solution-oriented infrastructure', 4.36, 'ligula pellentesque ultrices phasellus', 'Subin', 13);

INSERT INTO albums (title, song_count, artist) values ('quam nec', 11, 'Transcof');
INSERT INTO albums (title, song_count, artist) values ('morbi', 28, 'Stim');
INSERT INTO albums (title, song_count, artist) values ('justo sollicitudin', 18, 'Temp');
INSERT INTO albums (title, song_count, artist) values ('condimentum id luctus nec', 4, 'Bitwolf');
INSERT INTO albums (title, song_count, artist) values ('ac', 8, 'Treeflex');
INSERT INTO albums (title, song_count, artist) values ('nulla suspendisse potenti cras', 20, 'Viva');
INSERT INTO albums (title, song_count, artist) values ('felis ut at dolor', 15, 'Keylex');
INSERT INTO albums (title, song_count, artist) values ('sed', 12, 'Bitchip');
INSERT INTO albums (title, song_count, artist) values ('pharetra magna', 17, 'Zathin');
INSERT INTO albums (title, song_count, artist) values ('odio cras mi pede', 13, 'Transcof');

INSERT INTO artists (name, band_members, genre) values ('Bytecard', 'Vaclav', 'BRL');
INSERT INTO artists (name, band_members, genre) values ('Asoka', 'Thorin', 'HRK');
INSERT INTO artists (name, band_members, genre) values ('Latlux', 'Hilario', 'SEK');
INSERT INTO artists (name, band_members, genre) values ('Bamity', 'Morten', 'CNY');
INSERT INTO artists (name, band_members, genre) values ('Opela', 'Westbrook', 'MGA');
INSERT INTO artists (name, band_members, genre) values ('Duobam', 'Emmet', 'EUR');
INSERT INTO artists (name, band_members, genre) values ('Veribet', 'Valentijn', 'ZMW');
INSERT INTO artists (name, band_members, genre) values ('Konklux', 'Dukey', 'PLN');
INSERT INTO artists (name, band_members, genre) values ('Sonsing', 'Jocko', 'CNY');
INSERT INTO artists (name, band_members, genre) values ('Subin', 'Ferrell', 'CUP');
INSERT INTO artists (name, band_members, genre) values ('Quo Lux', 'Creigh', 'EUR');
INSERT INTO artists (name, band_members, genre) values ('Bigtax', 'Eb', 'EUR');
INSERT INTO artists (name, band_members, genre) values ('Zoolab', 'Donny', 'USD');
INSERT INTO artists (name, band_members, genre) values ('Stringtough', 'Jess', 'MYR');
INSERT INTO artists (name, band_members, genre) values ('Viva', 'Cobbie', 'PLN');

INSERT INTO playlists (name, song) values ('imperdiet et', 'Persevering grid-enabled algorithm');
INSERT INTO playlists (name, song) values ('posuere cubilia curae', 'Enterprise-wide fault-tolerant toolset');
INSERT INTO playlists (name, song) values ('sagittis dui vel', 'Fully-configurable disintermediate capacity');
INSERT INTO playlists (name, song) values ('mauris ullamcorper purus', 'Multi-layered context-sensitive archive');
INSERT INTO playlists (name, song) values ('tristique', 'Team-oriented upward-trending paradigm');
INSERT INTO playlists (name, song) values ('auctor gravida sem', 'Triple-buffered scalable attitude');
INSERT INTO playlists (name, song) values ('commodo placerat praesent', 'Automated encompassing capacity');
INSERT INTO playlists (name, song) values ('quisque arcu libero', 'Polarised global monitoring');
INSERT INTO playlists (name, song) values ('non pretium quis', 'Grass-roots radical success');
INSERT INTO playlists (name, song) values ('nisl', 'Innovative full-range conglomeration');
INSERT INTO playlists (name, song) values ('quis', 'Reverse-engineered stable forecast');
INSERT INTO playlists (name, song) values ('in congue', 'Profound web-enabled encryption');
INSERT INTO playlists (name, song) values ('luctus', 'Compatible responsive info-mediaries');
INSERT INTO playlists (name, song) values ('maecenas pulvinar', 'Focused contextually-based interface');
INSERT INTO playlists (name, song) values ('nisi nam ultrices', 'Networked bottom-line knowledge base');
INSERT INTO playlists (name, song) values ('tristique', 'Reduced value-added encoding');
INSERT INTO playlists (name, song) values ('diam', 'Realigned holistic product');
INSERT INTO playlists (name, song) values ('nisl aenean', 'Multi-tiered secondary moratorium');
INSERT INTO playlists (name, song) values ('nisl nunc nisl', 'Multi-layered solution-oriented framework');
INSERT INTO playlists (name, song) values ('et magnis dis', 'User-friendly global encryption');
INSERT INTO playlists (name, song) values ('mauris enim', 'Enhanced system-worthy adapter');
INSERT INTO playlists (name, song) values ('et', 'Extended hybrid function');
INSERT INTO playlists (name, song) values ('augue', 'Open-architected clear-thinking help-desk');
INSERT INTO playlists (name, song) values ('volutpat sapien', 'Team-oriented didactic product');
INSERT INTO playlists (name, song) values ('platea dictumst', 'Streamlined motivating encryption');
INSERT INTO playlists (name, song) values ('lacus', 'Automated discrete definition');
INSERT INTO playlists (name, song) values ('congue', 'Managed 24/7 strategy');
INSERT INTO playlists (name, song) values ('risus semper', 'Vision-oriented explicit frame');
INSERT INTO playlists (name, song) values ('tempus semper', 'Organic hybrid time-frame');
INSERT INTO playlists (name, song) values ('in hac habitasse', 'Advanced encompassing budgetary management');
